### ISSUE TITLE
Before anyone claims issues with audio volume read this...

### ISSUE THREAD

**Issue by dray-cyber** [dray-cyber/googlecontroller#1]
The volume now gets auto converted from say 100 to 1 99 to .99, you can just type your audio number in normally .I changed it as I thought it would help new people who use this library to remember.

**Comment by Dwarvy** [comment]
I tried to change the volume to 50%, but it just changes it to 0 instead. I also tried to put in decimal numbers in case I was using the old version, but that also changes the volume to 0.

What I tried:
0.5
50
50.0

Anything 100 and above changes the volume to 100, anything below 100 changes it to 0.

Any idea what might cause this?

I'm using a raspberry pi 3 with raspbian and python 3.5.3

**Comment by dray-cyber** [comment]
No clue, I'll check everything out.It works for me.

**Comment by dray-cyber** [comment]
Ah, I believe it to be the version of python.Mine is running from 3.8+.A syntax change in PyChromeCast or another dependency.Try it on a higher version!

**Comment by dray-cyber** [comment]
I await your reply, I triple checked the code and everything is as intended.The pychromecast module package runs the volume like 0.5 for 50 percent.I just have a little code in their to translate it.So it must be the python version.Ill do a deeper dive if that is not the case.

**Comment by peterd550** [comment]
I'm sorry 
I don't think this is for me.
I have no issues with you app

The only issues I've ever had was the dependies and that was an easy issue to resolve.

**Comment by dray-cyber** [comment]
> I'm sorry 
> I don't think this is for me.
> I have no issues with you app
> 
> The only issues I've ever had was the dependies and that was an easy issue to resolve.

?I don't understand, but if it's just a notice thank-you either way.If this has issues. Let me know.

**Comment by capedra** [comment]
Only volume that currently works is 100. Everything else mutes the music that is playing. From 0 to 99 it doesn't work at all.

**Comment by capedra** [comment]
@dray-cyber Btw, congrats for this great library !!

**Comment by Flairings** [comment]
Correct, anything above 0 and below 100 results in 0. anything 100 or above results in 100, please fix.

**Comment by dray-cyber** [comment]
> Correct, anything above 0 and below 100 results in 0. anything 100 or above results in 100, please fix.

At this point I can not find out anything that works.Greatly sorry for wasting everyone's time.This is now officially broken and will no longer be updated.If you are better at python then I take a shot at this problem.Fork this repo, do what you must.

**Comment by dray-cyber** [comment]
> @dray-cyber Btw, congrats for this great library !!

Would be greater if it worked....

**Comment by capedra** [comment]
@dray-cyber Let's try to solve this. I'm a python programmer.

**Comment by capedra** [comment]
@dray-cyber 
Maybe you should do this:
```
set_volume(float(percent / 100))
```
or this:
```
volume = min(max(0, volume), 1)
```
It seems to be a float issue.

**Comment by capedra** [comment]
@dray-cyber
Could you please provide the source code on here so we can solve this?
Thanks!

**Comment by capedra** [comment]
@dray-cyber Where's the set_volume function?

**Comment by dray-cyber** [comment]
> @dray-cyber 
> Maybe you should do this:
> ```
> set_volume(float(percent / 100))
> ```
> or this:
> ```
> volume = min(max(0, volume), 1)
> ```
> It seems to be a float issue.
> 

Actually that part is perfect, the issue is audio will not stream now.

**Comment by dray-cyber** [comment]
> @dray-cyber Where's the set_volume function? 

It would be in __init__.py.

**Comment by dray-cyber** [comment]
> > @dray-cyber Where's the set_volume function? 
> 
> It would be in init.py.It would be under def volume

**Comment by dray-cyber** [comment]
> @dray-cyber Let's try to solve this. I'm a python programmer. 

Sorry for the late responses, part of the reason I really can't keep up with this repository.

**Comment by dray-cyber** [comment]
seems all of this is working now...
