### ISSUE TITLE
say function doesn't work on Google Home Mini

### ISSUE THREAD

**Issue by havidarou** [dray-cyber/googlecontroller#2]
Hello,
I tested this module and both the mp3 and volume functions do work, but say does nothing on a Google Home.

Regards,
Javier.

**Comment by dray-cyber** [comment]
Thank you for that information, I am now assuming pychromecast has changed.I will try to find the version I used so I can just steal some of its connection code.

**Comment by dray-cyber** [comment]
For now you may have to roll back PyChromeCast to previous versions. I am currently checking if 7.7.1 is compatible.I am assuming it is as that is what was installed.

**Comment by dray-cyber** [comment]
I won't be able to check much right now as my Google home is in a different location.If you have yours available, just keep rolling back more versions if you want.

**Comment by peterd550** [comment]
I am having the same issue
I have my python in a docker container and I have not changed anything,
Also I have my version's in a requirements file. It has just stopped working.
My Versions are
asn1crypto==0.24.0
casttube==0.2.1
certifi==2020.12.5
chardet==4.0.0
cryptography==2.6.1
entrypoints==0.3
googlecontroller==3.0.6
idna==2.10
ifaddr==0.1.7
keyring==17.1.1
keyrings.alt==3.1.1
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.1.0
protobuf==3.15.7
PyChromecast==9.1.1
pycrypto==2.6.1
Pygments==2.3.1
PyGObject==3.30.4
pyxdg==0.25
PyYAML==3.13
requests==2.25.1
SecretStorage==2.3.1
six==1.12.0
urllib3==1.26.4

**Comment by dray-cyber** [comment]
Until I can get back to my Google home(might have lost it) roll back to previous versions of pychromecast, if that doesn't work try rolling back both PyChromeCast and python.For PyChromeCast, pip install PyChromeCast==7.7.0 (7.7.0 is a random version) for python reinstall from web.

**Comment by dray-cyber** [comment]
Roll back to that version(7.0.0 and below), as it's past 3 months ago.That is when the last commit was pushed and I believe I used that.If not use the version from 7 months prior to this day.

**Comment by peterd550** [comment]
I have been using PyChromecast==9.1.1 for the last 2 months with now issue.
As above it just stopped work 
Can you please advise if it is an issue with the  PyChromecast service?

**Comment by peterd550** [comment]
Don't ask my why but I had a play with versions then I thought just re run my master branch of my code and it just worked first time - so my requirements.txt file had no charge's 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by dray-cyber** [comment]
> I have been using PyChromecast==9.1.1 for the last 2 months with no issue.
> As above it just stopped work 
> Can you please advise if it is an issue with the  PyChromecast service? I can't at the moment I am truly sorry.requirments.txt says install the latest version so it always changes.I have no access to anything google related.I am truly sorry at this moment.

**Comment by dray-cyber** [comment]
To anyone who has access I encourage you to fork this repo and I wish you luck finding the problem.

**Comment by dray-cyber** [comment]
Versions being weird try changing if problem appears...
