### ISSUE TITLE
unable to play local mp3

### ISSUE THREAD

**Issue by peterd550** [dray-cyber/googlecontroller#3]
unable to play local mp3 in my docker container
Im using 
#!/usr/bin/env python3

from googlecontroller import GoogleAssistant
from googlecontroller.http_server import serve_file # for local files
host = "10.0.0.1"
home = GoogleAssistant(host=host)
file_url = serve_file("/home/scripts/HappyBirthdaySong.mp3", "audio/mp3") # local
home.play(file_url, "audio/mp3")

my pip3 installs are 
asn1crypto==0.24.0
casttube==0.2.1
certifi==2020.12.5
chardet==4.0.0
cryptography==2.6.1
entrypoints==0.3
googlecontroller==3.0.6
idna==2.10
ifaddr==0.1.7
keyring==17.1.1
keyrings.alt==3.1.1
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.1.0
protobuf==3.15.7
PyChromecast==9.1.1
pycrypto==2.6.1
Pygments==2.3.1
PyGObject==3.30.4
pyxdg==0.25
PyYAML==3.13
requests==2.25.1
SecretStorage==2.3.1
six==1.12.0
urllib3==1.26.4
zeroconf==0.29.0

My volume s set 50% on my google nest

the 
home.say("test") works well.

Please advise on a solution

**Comment by dray-cyber** [comment]
Interesting, the speak commands are working now?I thought they bricked themselves a while ago, I will still try to check on the mp3s not working!

**Comment by peterd550** [comment]
Yer I found the say function stopped working but I rebuilt my container with the same requirements.txt and it all worked 😄

**Comment by dray-cyber** [comment]
Oh yeah, does it just not work/no sound or does it spit a error?

**Comment by dray-cyber** [comment]
I might have a solution either way, I'll try to have a test out in 50 mins...

**Comment by dray-cyber** [comment]
So that was a lie, either way copy googlecontroller folder to the rest of the modules.After deleting previous.No pip install atm as this is experimental...Then try home.serve_media("HappyBirthdaySong.mp3", "C:\Users\YourUser\Desktop\") Only folder of file location not file itself.So make sure to do the full path!Everything but the file.That is a example if it was on a windows desktop!Do try I believe that will fix it!

**Comment by dray-cyber** [comment]
I attempted to add a whole new function, it should allow it to stream normally...

**Comment by dray-cyber** [comment]
Actually just reinstall via pypi!

**Comment by dray-cyber** [comment]
make sure to do pip install googlecontroller==3.5

**Comment by peterd550** [comment]
Thanks
I have tried all in the comments
Im still having no luck
when I use
#!/usr/bin/env python3

from googlecontroller import GoogleAssistant
from googlecontroller.http_server import serve_file # for local files
host = "10.0.0.1"
home = GoogleAssistant(host=host)
file_url = serve_file("/home/scripts/", "audio/mp3") # local
or
file_url = serve_file("/home/scripts/HappyBirthdaySong.mp3", "audio/mp3") # local
home.play(file_url, "audio/mp3")

i get the error
Well Hello!
Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    from googlecontroller import GoogleAssistant
  File "/home/busybox/.local/lib/python3.7/site-packages/googlecontroller/__init__.py", line 7, in <module>
    print(local_ip)
NameError: name 'local_ip' is not defined

**Comment by dray-cyber** [comment]
Well Hello isn't a error its a greeting, thankfully that ip issue should be a simple fix

**Comment by dray-cyber** [comment]
Just gotta remove that 1 line of printing it and you should be all good!

**Comment by dray-cyber** [comment]
https://pypi.org/project/googlecontroller/3.6/

**Comment by dray-cyber** [comment]
and run it all again, if it works I will update that documentation!

**Comment by dray-cyber** [comment]
also use the new serve_media function as I stated before in a few comments above!

**Comment by dray-cyber** [comment]
ok so that doesnt work
however I have come up with a solution!

**Comment by dray-cyber** [comment]
certainly not elegant

**Comment by dray-cyber** [comment]
Its done! Just gotta make a pypi now! and finish documentation!

**Comment by dray-cyber** [comment]
https://pypi.org/project/googlecontroller/5/ from 3.6 to five, yeah this took a lot of my life

**Comment by dray-cyber** [comment]
uninstall and reinstall package via pip, gl open a new issue if errors arrise!
