### ISSUE TITLE
Still can not play mp3

### ISSUE THREAD

**Issue by peterd550** [dray-cyber/googlecontroller#7]
Error
172.19.0.2
Traceback (most recent call last):
  File "./Good-Morning.py", line 4, in <module>
    from googlecontroller.http_server import serve_file # for local files
ModuleNotFoundError: No module named 'googlecontroller.http_server'

Code
/usr/bin/env python3

from googlecontroller import GoogleAssistant
from googlecontroller.http_server import serve_file # for local files

host1 = "10.0.0.14" #lounge
opentunnel = 0
home.serve_media("5Seconds.mp3", "/home/scripts/", opentunnel)

googlecontroller version 5.8 on a RPI4

**Comment by dray-cyber** [comment]
Ah gotcha

**Comment by dray-cyber** [comment]
Alrighty I think I gotcha covered now

**Comment by dray-cyber** [comment]
Try downloading the new init.py file and replace the one on your raspi can't reinstall yet as I can not upload the changes to pypi yet.

**Comment by peterd550** [comment]
That's a little out of my league.
I think I'll wait to upload to pypi :)

**Comment by dray-cyber** [comment]
Alrighty though it might be a while!

**Comment by peterd550** [comment]
Hey
Have you managed to get the fix into pipy?

**Comment by peterd550** [comment]
Is there any change with this request?

**Comment by dray-cyber** [comment]
Oh my god, I forgot!!! Ill get it ready today. been a rough few months sorry!

**Comment by peterd550** [comment]
Np
Please let me know when it's in pypi

**Comment by dray-cyber** [comment]
It is on there, forgot again, have poor memory, sorry!
